baseurl: /tamper
markdown: kramdown
title: Tamper
description: Tamper is a serialization protocol for categorical data.
github:
  repo: https://github.com/NYTimes/tamper
  wiki: https://github.com/NYTimes/tamper/wiki
exclude: 
    - build.sh
